// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: cart.sql

package db

import (
	"context"
)

const createCart = `-- name: CreateCart :one
INSERT INTO carts (
  owner,
  product,
  quantity
) VALUES (
  $1, $2, $3
) RETURNING owner, product, quantity
`

type CreateCartParams struct {
	Owner    string `json:"owner"`
	Product  string `json:"product"`
	Quantity int64  `json:"quantity"`
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRowContext(ctx, createCart, arg.Owner, arg.Product, arg.Quantity)
	var i Cart
	err := row.Scan(&i.Owner, &i.Product, &i.Quantity)
	return i, err
}
