// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: product.sql

package db

import (
	"context"
)

const createproduct = `-- name: Createproduct :one
INSERT INTO products(
    name,
    description,
    price
    ) VALUES (
        $1, $2, $3
    )
RETURNING name, description, price
`

type CreateproductParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int64  `json:"price"`
}

func (q *Queries) Createproduct(ctx context.Context, arg CreateproductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createproduct, arg.Name, arg.Description, arg.Price)
	var i Product
	err := row.Scan(&i.Name, &i.Description, &i.Price)
	return i, err
}
