// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc_login_user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserRequest) Reset()         { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()    {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbcaaa8f99023a3b, []int{0}
}

func (m *LoginUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserRequest.Unmarshal(m, b)
}
func (m *LoginUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserRequest.Marshal(b, m, deterministic)
}
func (m *LoginUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserRequest.Merge(m, src)
}
func (m *LoginUserRequest) XXX_Size() int {
	return xxx_messageInfo_LoginUserRequest.Size(m)
}
func (m *LoginUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserRequest proto.InternalMessageInfo

func (m *LoginUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginUserResponse struct {
	User                  *User                `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	SessionId             string               `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AccessToken           string               `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken          string               `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessTokenExpiresAt  *timestamp.Timestamp `protobuf:"bytes,5,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshTokenExpiresAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *LoginUserResponse) Reset()         { *m = LoginUserResponse{} }
func (m *LoginUserResponse) String() string { return proto.CompactTextString(m) }
func (*LoginUserResponse) ProtoMessage()    {}
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbcaaa8f99023a3b, []int{1}
}

func (m *LoginUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserResponse.Unmarshal(m, b)
}
func (m *LoginUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserResponse.Marshal(b, m, deterministic)
}
func (m *LoginUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserResponse.Merge(m, src)
}
func (m *LoginUserResponse) XXX_Size() int {
	return xxx_messageInfo_LoginUserResponse.Size(m)
}
func (m *LoginUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserResponse proto.InternalMessageInfo

func (m *LoginUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginUserResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *LoginUserResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginUserResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *LoginUserResponse) GetAccessTokenExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.AccessTokenExpiresAt
	}
	return nil
}

func (m *LoginUserResponse) GetRefreshTokenExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.RefreshTokenExpiresAt
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginUserRequest)(nil), "pb.LoginUserRequest")
	proto.RegisterType((*LoginUserResponse)(nil), "pb.LoginUserResponse")
}

func init() {
	proto.RegisterFile("rpc_login_user.proto", fileDescriptor_fbcaaa8f99023a3b)
}

var fileDescriptor_fbcaaa8f99023a3b = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xcd, 0x4e, 0xc3, 0x30,
	0x10, 0x84, 0xd5, 0x52, 0xaa, 0x76, 0x5b, 0x24, 0xb0, 0x8a, 0x08, 0x01, 0x04, 0x94, 0x0b, 0x27,
	0x47, 0x82, 0x27, 0x00, 0xa9, 0x07, 0x10, 0x17, 0x4a, 0xb9, 0x70, 0x89, 0xf2, 0xb3, 0x4d, 0x2d,
	0x9a, 0xd8, 0x78, 0x1d, 0xc1, 0xe3, 0xf1, 0x68, 0xc8, 0x76, 0x53, 0xc2, 0x89, 0x9b, 0x67, 0x76,
	0xfc, 0xed, 0x6a, 0x60, 0xa2, 0x55, 0x16, 0xaf, 0x65, 0x21, 0xaa, 0xb8, 0x26, 0xd4, 0x5c, 0x69,
	0x69, 0x24, 0xeb, 0xaa, 0x34, 0x84, 0x5f, 0x1d, 0x9e, 0x17, 0x52, 0x16, 0x6b, 0x8c, 0x9c, 0x4a,
	0xeb, 0x65, 0x64, 0x44, 0x89, 0x64, 0x92, 0x52, 0xf9, 0xc0, 0xf4, 0x11, 0xf6, 0x9f, 0x2c, 0xe4,
	0x95, 0x50, 0xcf, 0xf1, 0xa3, 0x46, 0x32, 0x2c, 0x84, 0x81, 0x45, 0x54, 0x49, 0x89, 0x41, 0xe7,
	0xa2, 0x73, 0x3d, 0x9c, 0x6f, 0xb5, 0x9d, 0xa9, 0x84, 0xe8, 0x53, 0xea, 0x3c, 0xe8, 0xfa, 0x59,
	0xa3, 0xa7, 0xdf, 0x5d, 0x38, 0x68, 0xc1, 0x48, 0xc9, 0x8a, 0x90, 0x9d, 0x42, 0xcf, 0xfe, 0x76,
	0xa4, 0xd1, 0xcd, 0x80, 0xab, 0x94, 0xbb, 0xb9, 0x73, 0xd9, 0x19, 0x00, 0x21, 0x91, 0x90, 0x55,
	0x2c, 0x1a, 0xe2, 0x70, 0xe3, 0x3c, 0xe4, 0xec, 0x12, 0xc6, 0x49, 0x96, 0x21, 0x51, 0x6c, 0xe4,
	0x3b, 0x56, 0xc1, 0x8e, 0x0b, 0x8c, 0xbc, 0xb7, 0xb0, 0x16, 0xbb, 0x82, 0x3d, 0x8d, 0x4b, 0x8d,
	0xb4, 0xda, 0x64, 0x7a, 0x2e, 0x33, 0xde, 0x98, 0x3e, 0xf4, 0x0c, 0x47, 0x6d, 0x4e, 0x8c, 0x5f,
	0x4a, 0x68, 0xa4, 0x38, 0x31, 0xc1, 0xae, 0xbb, 0x2b, 0xe4, 0xbe, 0x29, 0xde, 0x34, 0xc5, 0x17,
	0x4d, 0x53, 0xf3, 0x49, 0x6b, 0xdd, 0xcc, 0x7f, 0xbc, 0x33, 0xec, 0x05, 0x82, 0x3f, 0x7b, 0xdb,
	0xcc, 0xfe, 0xbf, 0xcc, 0xc3, 0xf6, 0x79, 0x5b, 0xe8, 0xfd, 0xc9, 0xdb, 0x71, 0x21, 0xcc, 0xaa,
	0x4e, 0x79, 0x26, 0xcb, 0x28, 0x4f, 0x48, 0x9a, 0x3c, 0x9a, 0xd9, 0xb7, 0x4a, 0xd3, 0xbe, 0xe3,
	0xdc, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x5e, 0xdd, 0x20, 0xfb, 0x01, 0x00, 0x00,
}
